sequenceDiagram
    participant browser
    participant server

    browser->>server: POST https://studies.cs.helsinki.fi/exampleapp/new_note_spa
    Note right of browser: The POST request has the new note in JSON format, as indicated by the Content-Type 
    Note right of browser: The structure of the <form> tag has the attribute 'type' set to 'submit' and the attribute 'value' set to 'save'.
    Note right of browser: A JavaScript file processes it to determine the types of dates, possibly formatting them as JSON.
    activate server
    server-->>browser: 201 created
    deactivate server

   